import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rithvik Pallamreddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="overflow-x-hidden" lang="en">
      <body
        className={`${inter.className} min-h-[100dvh] grid grid-rows-[auto_1fr_auto]`}
      >
        <Navbar />
        <div className="mt-20">
          {children}
          <Footer />
          <Toaster />
        </div>
      </body>
    </html>
  );
}
